@startuml Basic Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

Boundary(foo, "Finance", "Domain") {
    Boundary(c1, "Subdomain1", "Subdomain") {
        System(system1, "System 1")
    }
    Boundary(s2, "Subdomain2", "Subdomain") {
        System(system2, "System 2", "does something amazing")
        System(system3, "System 3")
    }
}
'Rel(system1, system2, "notifies", "HTTPS")
'Rel(system2, system3, "files")

@enduml
